// OWNER A. Stages 0-2: the brief, the generated sections, the CVs.
// Sections are generated by the model and then CONFIRMED BY A HUMAN before
// anything downstream runs. That confirmation step is the product, not a formality.
import { useState } from 'react'

import { api, ApiFailure } from '../../api/client'
import { Button, Card, Field, Warnings } from '../../components/ui'
import type { AppState, Warning } from '../../types'

export function SetupScreen({ state, patch }: {
  state: AppState
  patch: (p: Partial<AppState>) => void
}) {
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<Warning[]>([])

  async function generateProject() {
    setBusy(true); setError([])
    try {
      patch({ project: await api.project(state.brief) })
    } catch (e) {
      const f = e as ApiFailure
      setError([{ code: f.code, severity: 'error', message: f.message }])
    } finally {
      setBusy(false)
    }
  }

  return (
    <div style={{ display: 'grid', gap: 16 }}>
      <Card title="1 — What are you building?">
        <Field label="Project brief" rows={5} value={state.brief}
               placeholder="Five sentences are enough. What it does, who it is for, what has to exist by the deadline."
               onChange={v => patch({ brief: v })} />
        <div><Button onClick={generateProject} disabled={busy || state.brief.length < 20}>
          {busy ? 'Reading the brief…' : 'Generate sections'}
        </Button></div>
        <Warnings items={error} />
      </Card>

      {state.project && (
        <Card title="2 — Confirm the sections"
              right={<span style={{ fontSize: 12, color: 'var(--ink-3)' }}>
                {state.project.horizonBlocks} blocks · {state.project.sections.length} sections
              </span>}>
          <p style={{ margin: 0, color: 'var(--ink-2)', fontSize: 14 }}>
            Everything downstream references these. Edit them now, not later.
          </p>
          {/* TODO A: make each section editable, and allow add and delete. */}
          <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'grid', gap: 8 }}>
            {state.project.sections.map(s => (
              <li key={s.id} style={{
                border: '1px solid var(--rule)', borderRadius: 'var(--radius)', padding: '10px 12px',
              }}>
                <strong>{s.name}</strong>
                <span className="mono" style={{ fontSize: 11, color: 'var(--ink-3)', marginLeft: 8 }}>{s.id}</span>
                <div style={{ fontSize: 14, color: 'var(--ink-2)' }}>{s.description}</div>
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* TODO A: stage 3 — upload one CV per person, five parallel calls to api.cv,
          then an editable profile card per person with the evidence quote on hover. */}
    </div>
  )
}
