"""CLI: python -m task_assigner team.md tasks.json -o assignment.json"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from .assigner import AssignerConfig, AssignmentError, TaskAssigner


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="python -m task_assigner",
        description="Assign a team to a validated task list and order each member's work.",
    )
    p.add_argument("team_md", type=Path, help="team.md as generated by the brief pipeline")
    p.add_argument("tasks_json", type=Path,
                   help="task planner output: flat task list, {nodes, edges} graph, or the API envelope")
    p.add_argument("-o", "--output", type=Path, help="write the assignment JSON here (default: stdout)")
    p.add_argument("--model", default=AssignerConfig.model)
    p.add_argument("--thinking-level", default=AssignerConfig.thinking_level,
                   help="Gemini 3 thinking level (low/medium/high); 'none' to unset")
    p.add_argument("--thinking-budget", type=int, help="Gemini 2.5 thinking budget (-1 = dynamic)")
    p.add_argument("--max-fix-rounds", type=int, default=AssignerConfig.max_fix_rounds)
    p.add_argument("--max-idle-fraction", type=float, default=AssignerConfig.max_idle_fraction)
    p.add_argument("--allow-invalid", action="store_true",
                   help="write the assignment even if validation still fails after all rounds")
    p.add_argument("--show-schedule", action="store_true",
                   help="print the simulated schedule (hour range and members per task) to stderr")
    args = p.parse_args(argv)

    cfg = AssignerConfig(
        model=args.model,
        thinking_level=None if args.thinking_level in (None, "none") else args.thinking_level,
        thinking_budget=args.thinking_budget,
        max_fix_rounds=args.max_fix_rounds,
        max_idle_fraction=args.max_idle_fraction,
    )
    # Explicit UTF-8: Windows would otherwise decode with the locale code page.
    team_md = args.team_md.read_text(encoding="utf-8")
    tasks = json.loads(args.tasks_json.read_text(encoding="utf-8"))

    try:
        result = TaskAssigner(config=cfg).assign(team_md, tasks)
    except (AssignmentError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    v = result.validation
    print(f"{len(result.members)} members, {len(result.tasks)} tasks, "
          f"{result.rounds} round(s): {v.summary()}", file=sys.stderr)
    for w in v.warnings:
        print(f"  warning: {w}", file=sys.stderr)
    for e in v.errors:
        print(f"  ERROR: {e}", file=sys.stderr)
    for n in result.assignment.get("notes", []):
        print(f"  note: task {n['task_id']} / {n['name']}: {n['note']}", file=sys.stderr)

    if args.show_schedule and v.schedule:
        by_id = {t["id"]: t for t in result.tasks}
        doing: dict[int, list[str]] = {}
        for person in result.assignment["people"]:
            for tid in person["task_ids"]:
                doing.setdefault(tid, []).append(person["name"])
        for tid, (start, end) in sorted(v.schedule.items(), key=lambda kv: (kv[1], kv[0])):
            print(f"  h {start:>3}-{end:<3} task {tid} ({by_id[tid]['name']}): "
                  f"{', '.join(doing.get(tid, []))}", file=sys.stderr)

    if not result.ok and not args.allow_invalid:
        print("assignment rejected; use --allow-invalid to write it anyway", file=sys.stderr)
        return 1

    payload = json.dumps(result.assignment, indent=2, ensure_ascii=False)
    if args.output:
        args.output.write_text(payload + "\n", encoding="utf-8")
        print(f"wrote {args.output}", file=sys.stderr)
    else:
        print(payload)
    return 0


if __name__ == "__main__":
    sys.exit(main())
