import { GripVertical, UsersRound } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Card } from '../../components/ui'
import { Timeline } from '../../components/timeline/Timeline'
import type { AppState } from '../../types'

export function AssignmentScreen({ state, reassign }: { state: AppState; reassign: (taskId: string, personId: string) => void }) {
  const [draggedTask, setDraggedTask] = useState<string | null>(null)
  const taskTitle = (id: string) => state.graph?.tasks.find(task => task.id === id)?.title ?? id
  const work = useMemo(() => Object.fromEntries(state.people.map(person => [person.id, state.plan?.assignments.filter(a => a.personId === person.id).reduce((sum, assignment) => sum + assignment.endBlock - assignment.startBlock, 0) ?? 0])), [state.people, state.plan])
  if (!state.plan || !state.graph) return <main id="main-content" className="screen screen-assignment"><div className="screen-heading"><div><p className="eyebrow">03 · Assignment</p><h2>Put the right people on the right work.</h2><p>Generate a plan in Task flow first; assignments will appear here for human review.</p></div></div><div className="empty"><div><UsersRound size={28} aria-hidden="true" /><strong style={{ display: 'block' }}>No assignment plan yet</strong><span className="subtle">Go to Task flow and choose “Generate plan”.</span></div></div></main>
  return <main id="main-content" className="screen screen-assignment"><div className="screen-heading"><div><p className="eyebrow">03 · Assignment</p><h2>Review the team plan, then make it yours.</h2><p>Drag a task onto a teammate or use the responsible-person menu. Every manual edit is locked and remains on re-plan.</p></div><span className="pill">{state.plan.metrics?.parallelismScore?.toFixed(2) ?? '—'} parallelism</span></div>
    <p className="subtle" id="assignment-help">Drag a task to a teammate on the left, or choose the teammate in the menu. The menu is the keyboard alternative to drag and drop.</p>
    <div className="assignment-layout"><Card title="Team capacity" right={<span className="subtle">30 min blocks</span>}><div>{state.people.map(person => { const blocks = work[person.id] ?? 0; const ratio = Math.min(100, blocks / Math.max(1, state.project?.horizonBlocks ?? 24) * 100); return <article key={person.id} className="assignment-person" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); const taskId = event.dataTransfer.getData('text/task-id') || draggedTask; if (taskId) reassign(taskId, person.id); setDraggedTask(null) }}><div className="person-top"><div className="avatar">{person.name.slice(0, 1)}</div><div><strong>{person.name}</strong><div className="subtle">{blocks} blocks assigned</div></div></div><div className="capacity" aria-label={`${person.name}: ${blocks} blocks assigned`}><span style={{ width: `${ratio}%` }} /></div></article> })}</div></Card>
      <div className="stack"><Card title="Task assignments" right={<span className="pill">{state.plan.assignments.length} assigned</span>}><div>{state.plan.assignments.map(assignment => <div className="assignment-row" key={assignment.taskId} draggable onDragStart={event => { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/task-id', assignment.taskId); setDraggedTask(assignment.taskId) }} onDragEnd={() => setDraggedTask(null)} aria-describedby="assignment-help"><div style={{ display: 'flex', gap: 10, alignItems: 'center' }}><GripVertical size={18} color="var(--ink-3)" aria-hidden="true" /><div><strong>{taskTitle(assignment.taskId)}</strong><div className="subtle">Block {assignment.startBlock + 1}–{assignment.endBlock}{assignment.locked ? ' · manually locked' : ''}</div></div></div><label><span className="field-label" style={{ display: 'block', marginBottom: 5 }}>Responsible person</span><select className="select" value={assignment.personId} onChange={event => reassign(assignment.taskId, event.target.value)} aria-label={`Responsible person for ${taskTitle(assignment.taskId)}`}>{state.people.map(person => <option value={person.id} key={person.id}>{person.name}</option>)}</select></label></div>)}</div></Card><Card title="Schedule at a glance"><Timeline state={state} onReassign={reassign} /></Card><Card title="Why this plan?">{state.people.map(person => state.plan?.rationale[person.id] && <p className="muted" style={{ margin: '0 0 10px' }} key={person.id}><strong style={{ color: 'var(--ink)' }}>{person.name}</strong> — {state.plan.rationale[person.id]}</p>)}</Card></div></div>
  </main>
}
