import { Check, CheckCircle2, GripVertical, LockKeyhole, ShieldCheck, UserRoundCheck } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Button, Card, Warnings } from '../../components/ui'
import { Timeline } from '../../components/timeline/Timeline'
import type { AppState } from '../../types'

const initials = (name: string) => name.split(/\s+/).slice(0, 2).map(part => part[0]).join('').toUpperCase()
export function AssignmentScreen({ state, reassign }: { state: AppState; reassign: (taskId: string, personId: string) => void }) {
  const [draggedTask, setDraggedTask] = useState<string | null>(null); const [approved, setApproved] = useState(false)
  const taskTitle = (id: string) => state.graph?.tasks.find(task => task.id === id)?.title ?? id
  const work = useMemo(() => Object.fromEntries(state.people.map(person => [person.id, state.plan?.assignments.filter(a => a.personId === person.id).reduce((sum, assignment) => sum + assignment.endBlock - assignment.startBlock, 0) ?? 0])), [state.people, state.plan])
  const maxWork = Math.max(1, ...Object.values(work))
  const matchFor = (taskId: string, personId: string) => { const task = state.graph?.tasks.find(item => item.id === taskId); const person = state.people.find(item => item.id === personId); const needs = state.project?.sections.find(item => item.id === task?.sectionId)?.needs ?? []; if (!person || !needs.length) return 76; const levels = person.skills.filter(skill => needs.includes(skill.category)).map(skill => skill.level); return levels.length ? Math.min(98, 66 + Math.round(levels.reduce((a, b) => a + b, 0) / levels.length * 7)) : 58 }
  if (!state.plan || !state.graph) return null
  return <main id="main-content" className="screen screen-assignment"><div className="screen-heading"><div><p className="eyebrow">04 · Assignments</p><h1>Review every suggestion. Keep the final say.</h1><p>Reassign work by drag and drop or with the accessible menus. Manual decisions are locked automatically.</p></div><div className={`review-status ${approved ? 'approved' : ''}`}>{approved ? <CheckCircle2 size={19} /> : <ShieldCheck size={19} />}<div><strong>{approved ? 'Plan approved' : 'Awaiting review'}</strong><small>{state.plan.assignments.length} assignments</small></div></div></div>
    <div className="assignment-summary"><div><span className="summary-number">{Math.round((state.plan.metrics?.parallelismScore ?? 0) * 100)}%</span><span>parallel work score</span></div><div><span className="summary-number">{state.plan.assignments.filter(item => item.locked).length}</span><span>manual decisions locked</span></div><div><span className="summary-number">{state.people.length}</span><span>people in the plan</span></div></div>
    <p className="subtle assignment-help" id="assignment-help">Drag a task onto a teammate in the capacity panel, or use its responsible-person menu. Both methods protect the change on regeneration.</p>
    <div className="assignment-layout"><Card title="Team capacity" right={<span className="subtle">Relative workload</span>}><div>{state.people.map(person => { const blocks = work[person.id] ?? 0; const ratio = Math.min(100, blocks / maxWork * 100); return <article key={person.id} className={`assignment-person ${draggedTask ? 'drop-ready' : ''}`} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); const taskId = event.dataTransfer.getData('text/task-id') || draggedTask; if (taskId) { reassign(taskId, person.id); setApproved(false) } setDraggedTask(null) }}><div className="person-top"><div className="avatar">{initials(person.name)}</div><div><strong>{person.name}</strong><div className="subtle">{blocks / 2}h assigned · {Math.round(ratio)}% load</div></div></div><div className="capacity" aria-label={`${person.name}: ${blocks / 2} hours assigned`}><span style={{ width: `${ratio}%` }} /></div><div className="person-availability"><Check size={13} /> Available for reassignment</div></article> })}</div></Card><div className="stack"><Card title="Suggested ownership" right={<span className="pill"><UserRoundCheck size={14} /> {state.plan.assignments.length} assigned</span>}><div className="assignment-list">{state.plan.assignments.map(assignment => { const person = state.people.find(item => item.id === assignment.personId); const score = matchFor(assignment.taskId, assignment.personId); return <article className="assignment-row" key={assignment.taskId} draggable onDragStart={event => { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/task-id', assignment.taskId); setDraggedTask(assignment.taskId) }} onDragEnd={() => setDraggedTask(null)} aria-describedby="assignment-help"><div className="drag-handle"><GripVertical size={18} aria-hidden="true" /></div><div className="assignment-copy"><div className="assignment-title"><strong>{taskTitle(assignment.taskId)}</strong>{assignment.locked && <span className="locked"><LockKeyhole size={12} /> Manual lock</span>}</div><div className="match-row"><span className="match-score">{score}% match</span><span>Block {assignment.startBlock + 1}–{assignment.endBlock}</span></div><p>{state.plan?.rationale[assignment.taskId] ?? `${person?.name ?? 'This teammate'} matches the task’s required skills and current capacity.`}</p></div><label className="assignment-select"><span className="field-label">Responsible person</span><select className="select" value={assignment.personId} onChange={event => { reassign(assignment.taskId, event.target.value); setApproved(false) }} aria-label={`Responsible person for ${taskTitle(assignment.taskId)}`}>{state.people.map(option => <option value={option.id} key={option.id}>{option.name}</option>)}</select></label></article> })}</div></Card><Card title="Schedule at a glance"><Timeline state={state} onReassign={reassign} /></Card><Warnings items={[...state.plan.risks, ...state.plan.issues]} /></div></div>
    <div className={`approval-card ${approved ? 'is-approved' : ''}`}><div className="approval-icon">{approved ? <CheckCircle2 size={24} /> : <ShieldCheck size={24} />}</div><div><h2>{approved ? 'Assignment plan approved' : 'Ready for final approval?'}</h2><p>{approved ? 'The reviewed ownership plan is ready to share with the team.' : 'Confirm that workload, ownership and manual overrides reflect your decision.'}</p></div><Button kind={approved ? 'secondary' : 'primary'} onClick={() => setApproved(value => !value)}>{approved ? 'Reopen review' : 'Approve final plan'}</Button></div>
  </main>
}
